version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retail_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: retail_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - .:/app